# Generated by Django 3.0.4 on 2020-03-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Description', models.CharField(max_length=500)),
                ('Topics', models.CharField(max_length=10)),
                ('Points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Description', models.CharField(max_length=500)),
                ('Topic', models.CharField(max_length=10)),
                ('Deadline', models.DateTimeField(verbose_name='deadline')),
                ('Complexity', models.IntegerField(default=1)),
            ],
        ),
    ]
