# Generated by Django 3.0.5 on 2020-04-05 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=100)),
                ('t_company', models.CharField(max_length=100)),
                ('t_details', models.CharField(max_length=400)),
            ],
        ),
        migrations.RenameField(
            model_name='boards',
            old_name='Description',
            new_name='b_description',
        ),
        migrations.RenameField(
            model_name='boards',
            old_name='Name',
            new_name='b_name',
        ),
        migrations.RenameField(
            model_name='boards',
            old_name='Points',
            new_name='b_points',
        ),
        migrations.RenameField(
            model_name='boards',
            old_name='Topics',
            new_name='b_topics',
        ),
        migrations.RenameField(
            model_name='cards',
            old_name='Complexity',
            new_name='c_complexity',
        ),
        migrations.RenameField(
            model_name='cards',
            old_name='Deadline',
            new_name='c_deadline',
        ),
        migrations.RenameField(
            model_name='cards',
            old_name='Description',
            new_name='c_description',
        ),
        migrations.RenameField(
            model_name='cards',
            old_name='Name',
            new_name='c_name',
        ),
        migrations.RenameField(
            model_name='cards',
            old_name='Topic',
            new_name='c_topic',
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=40)),
                ('u_username', models.CharField(max_length=80)),
                ('u_email', models.CharField(max_length=80)),
                ('u_admin', models.IntegerField(default=0)),
                ('u_team', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kanban.Teams')),
            ],
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=30)),
                ('list_position', models.IntegerField()),
                ('list_board', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kanban.Boards')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=20)),
                ('cat_board', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kanban.Boards')),
            ],
        ),
        migrations.AddField(
            model_name='boards',
            name='b_team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kanban.Teams'),
        ),
        migrations.AddField(
            model_name='cards',
            name='c_assigned',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kanban.Users'),
        ),
        migrations.AddField(
            model_name='cards',
            name='c_list',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kanban.Lists'),
        ),
    ]
