# Generated by Django 3.0.5 on 2020-05-28 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0002_auto_20200405_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='b_position',
            field=positions.fields.PositionField(default=-1),
        ),
        migrations.AlterField(
            model_name='users',
            name='u_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
