# Generated by Django 3.0.5 on 2020-05-28 16:52

from django.db import migrations
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_auto_20200528_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='b_position',
        ),
        migrations.AddField(
            model_name='cards',
            name='c_position',
            field=positions.fields.PositionField(default=-1),
        ),
    ]
