# Generated by Django 3.0.5 on 2020-05-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_auto_20200528_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='b_icon',
            field=models.CharField(default='.', max_length=500),
        ),
    ]
