# Generated by Django 3.0.5 on 2020-06-07 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_auto_20200528_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='finish')),
                ('complexity', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='boards',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='cards',
            name='c_board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kanban.Boards'),
        ),
    ]
