# Generated by Django 3.0.5 on 2020-05-28 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_boards_b_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='finish')),
                ('complexity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cards',
            name='c_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boards',
            name='b_icon',
            field=models.CharField(default='images/deficon.png', max_length=500),
        ),
    ]
